name: blocpreferences
description: Example of application preferences using BLoC pattern

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #some UI stuff
  searchable_dropdown: ^1.1.3

  #storing stuff
  shared_preferences: ^0.5.7

  #app state control
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0

  #functional programing
  either_option: ^1.0.6

  #dependency injection
  injectable: ^0.3.0
  get_it: ^4.0.1

  #utils
  equatable: ^1.1.1
  freezed_annotation: ^0.7.1

  #logging
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #build runner
  build_runner: ^1.9.0
  injectable_generator: ^0.3.4
  #for generating data classes
  freezed: ^0.10.7

  #lint rules
  lint: ^1.1.1

  #testing
  mockito: ^4.1.1
  bloc_test: ^5.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/i18n/


